Added version endpoint
iver-wharf/wharf-api pull request #2
Opened 2021-05-11 12:48 UTC by jilleJr

> For Iver employees: WO0000000663753

- Added version.go, populated by deploy/update-version.sh
- Update version from Dockerfile
- Added /version endpoint
- Updated CHANGELOG.md

2021-05-11 16:31 UTC, fredx30 commented on main.go
> +	"github.com/iver-wharf/wharf-api/docs"
This path does not appear to resolve.

2021-05-11 16:37 UTC, Pikabanga reviewed
Same comments as in https://github.com/iver-wharf/wharf-provider-github/pull/5

2021-05-12 07:02 UTC, Pikabanga requested changes
Flagging for requesting changes

2021-05-12 09:30 UTC, jilleJr commented on main.go
> +	"github.com/iver-wharf/wharf-api/docs"
It is generated by `swag init`

2021-05-24 07:38 UTC, fredx30 approved these changes

2021-05-31 07:38 UTC, Pikabanga approved these changes

2021-05-31 07:41 UTC, merged

2021-05-31 07:43 UTC, jilleJr commented
Oh gosh I merged before having 2 reviewers...

Got jinxed by `gh` CLI tool

```console
$ gh pr status
Relevant pull requests in iver-wharf/wharf-api

Current branch
  #2  Added version endpoint [feature/version-endpoint]
  ✓ Approved ✓ Up to date
```

It did say approved. :( Will check closer next time