Split rest of models
iver-wharf/wharf-api pull request #83
Opened 2021-09-28 15:35 UTC by jilleJr

- \[ ] I've added a new note in the `CHANGELOG.md` file, according to docs:
  https://iver-wharf.github.io/#/development/changelogs/writing-changelogs

## Summary

Lots have been changed here, so bare with me. One by one, I went through the following files and replaced all model usages with the new `pkg/model/database` models, and added models to `pkg/model/request` and `pkg/model/response` on demand:

- artifact.go
- test_result.go
- build.go
- ping.go
- provider.go
- project.go

Ran `swag init` as well as unit and manual tests between each file was converted.

Other changes:

- Removed database_models.go, database_models_json.go, and database_models_test.go
- Added `swaggertype:"object"` to `interface{}` as `swag init` was logging warnings about it
- Added `extensions:"x-nullable"` to `null.*` fields in request & response models

Behaviour should be almost identical to as before, except some more validation that has been added now.

## Motivation

I've intentionally made it so none of the `pkg/model/*` packages depend on each other. The integration between them is done in the `main` package, as can be seen by all the new `dbBranchToResponse`'esque mapping functions.

Another big thing is that the three model packages deal with enums in their own isolated way. While `pkg/model/request` and `pkg/model/response` use strings, the `pkg/model/database` can use ints. And mapping between these are done with `switch` statements, so no actual parsing or "to-string()'ing" is done.

Closes #72.

RFC-0016 states that the `request.{model}Update` models should not contain any IDs to the object itself, but that's deferred to the #70 issue, and this PR does not aim to tackle that one.

2021-09-29 10:58 UTC, Alexamakans approved these changes

2021-09-29 14:31 UTC, jilleJr commented
@Alexamakans There were some changes to deal with the merge conflics from #80 and #82, so I re-requested your review

2021-09-30 09:42 UTC, jilleJr commented
Codacy is warning about duplications, but those pop up because I touched the regarding code with my renames and struct usage changes.

I'm not planning on dealing with them, as they are remenant from older code, and will get dealt with in other PRs for the milestone.

Once approved, I will merge the PR despite the failing Codacy check.

2021-09-30 11:12 UTC, Alexamakans approved these changes

2021-10-06 07:22 UTC, Pikabanga requested changes

2021-10-06 07:22 UTC, Pikabanga commented on branch.go
> +			Message("Failed to replace branch list. Transaction reverted.")
Might as well use SQL nomenclature :)

```suggestion
			Message("Failed to replace branch list. Transaction rolled back.")
```

2021-10-06 07:37 UTC, jilleJr commented on branch.go
> +				Limit(1).
Good point!

2021-10-06 07:38 UTC, jilleJr commented on branch.go
> +			Message("Failed to replace branch list. Transaction reverted.")
Very nice!

2021-10-06 12:50 UTC, merged